### ISSUE TITLE
AMD Renoir (4xxx) (Zen 2)

### ISSUE THREAD

**Issue by ghost** [system76/laptop-suggestions#128]
### Why/User Benefit/User Problem
Notebooks with AMD 4000 series processors APU

### Description of the feature
Great energy savings, great power. Much better than their Intel equivalent.
https://en.wikichip.org/wiki/amd/cores/renoir

**Comment by eduncan911** [comment]
Please this.  It also shaves off a hundred or two dollars.

I hate paying the Intel tax, as well as the backdoor taxes.  Even with Coreboot, Intel still requires proprietary blobs loaded.

**Comment by briggs1978** [comment]
I have to imagine it's already on the horizon, but very much this.

**Comment by eduncan911** [comment]
I've literally been asking System76's Twitter for almost a year:

https://mobile.twitter.com/search?q=%40eduncan911%20system76%20amd&src=typed_query

**Comment by Dmole** [comment]
The competition is looking tempting

https://www.phoronix.com/scan.php?page=article&item=amd-ryzen5-4500u&num=1

**Comment by eduncan911** [comment]
> The competition is looking tempting
> 
> https://www.phoronix.com/scan.php?page=article&item=amd-ryzen5-4500u&num=1

Yes, especially since Lenovo can be ordered with Linux now and not paying the Microsoft tax.

Coreboot is also available for many variants of AMD, so there had been partnerships between them.  Now rather Renoir is included in those specs I do not know.

https://doc.coreboot.org/search.html?q=Amd&check_keywords=yes&area=default

Excluding the coreboot "feature", which can be implemented later with a BIOS update, there's no reason not to offer AMD.

Especially for those of us that run Qubes, with about a dozen VMs running on the system at any given time - almost always in use at the same time.  The nice phat 35W 4700GE 8C/16T CPU really is attractive here for many hundreds less than Intel's offering.

**Comment by ghost** [comment]
https://twitter.com/jeremy_soller/status/1286457590289858560?s=20

**Comment by eduncan911** [comment]
Well, the Pangolin has been announced!  **Guess we can close this thread now**.  :)

https://system76.com/laptops/pangolin

But still 1080p.  Dammit!!!

Pop_OS! has been the best 4k distro I've ever used (on non-System76 machines).  Perfection.  But, no 4k available to buy?!?!  Argh...

**Comment by ghost** [comment]
> Well, the Pangolin has been announced! **Guess we can close this thread now**. :)
> 
> https://system76.com/laptops/pangolin
> 
> But still 1080p. Dammit!!!
> 
> Pop_OS! has been the best 4k distro I've ever used (on non-System76 machines). Perfection. But, no 4k available to buy?!?! Argh...

Yass!
see you people : https://github.com/system76/laptop-suggestions/issues/143

**Comment by dylangerdaly** [comment]
Looks like everything is closed tho, UEFI + EC is all closed :-1:
